version: '3.9'

services:
  go-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: go-app
    volumes:
      - .:/src/app
    working_dir: /src/app
    ports:
      - 8080:8080
