name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      # Download and tidy dependencies
      - name: Download and tidy dependencies
        run: go mod download && go mod tidy

      # Build project
      - name: Build project
        run: go build -o main .
      
      # Run tests
      - name: Run tests
        run: go test -v ./...
